<div class="container mr-5">
    <div class="row">
        <div class="col">
            <img width="100%" src="https://contaazul-site-uploads.s3.amazonaws.com/uploads/2016/06/contaazul-giro-estoque.svg">
        </div>
        <div class="col">
            <h3 class="text-center">Login</h3>
            <form method="post" action="">
                <label for="email">EMAIL:</label>
                <input name="email" type="email" id="email" class="form-control" placeholder="Digite seu E-mail">
                <br>
                <label for="password">SENHA:</label>
                <input name="password" type="password" id="password" class="form-control" placeholder="Digite sua Senha">
                <br>
                <button class="btn btn-danger btn-lg btn-block">Entrar</button>
                <br>
            </form>
        </div>
    </div>
</div>