<div class="ml-5">
    <div class="btn-group">
        <a class="btn btn-danger" href="/dashboard" >
            Dashboard
        </a>
    </div>
    <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Produtos
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="/produto/listar">Listar</a></li>
            <li><a class="dropdown-item" href="/produto/adicionar">Adicionar</a></li>
        </ul>
    </div>
    <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            <?="Olá, " . ($user->login->nome)?>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="/logout">Sair</a></li>
        </ul>
    </div>
</div>