<h1>Cadastro de Produto</h1>

<form action="" method="post">
    <label for="nome">Nome</label>
    <input type="text" name="nome" id="nome" placeholder="Nome do Produto" class="form-control" required>
    <br>
    <label for="peso">Peso</label>
    <input type="text" name="peso" id="peso" placeholder="Peso" class="form-control" required>
    <br>
    <label for="quantidade">Quantidade Mínima</label>
    <input name="quantidade" id="quantidade" placeholder="Quantidade Mínima" class="form-control" required></input>
    <br>
    <label for="categoria">Categoria do Produto</label>
    <select class="form-select" name="categoria" aria-label="Categoria do Produto">
            <?php
                foreach ($categories as $category) {
                    echo "<option value='{$category->id}'>{$category->categoria}</option>";
                }
            ?>
    </select>
    <br>
    <label for="fornecedor">Fornecedor do Produto</label>
    <select class="form-select" name="fornecedor" aria-label="Fornecedor do Produto">
        <?php
        foreach ($suppliers as $supplier) {
            echo "<option value='{$supplier->id}'>{$supplier->fornecedor}</option>";
        }
        ?>
    </select>
    <br>

    <button class="btn btn-danger">Criar</button>
</form>
<hr>